---
rid: 1494600
bid: javascript
rcd: fetch
srcpath: javascript/fetch.adoc
title: Fetch API まとめ
category: JavaScript
date: 2017.7.17
layout: refill.jade
---

== Can I use... Fetch

A modern replacement for XMLHttpRequest.

- link:http://caniuse.com/#feat=fetch[Can I use... Support tables for HTML5, CSS3, etc]

== window.fetch polyfill

- link:https://github.com/github/fetch[]

[source,bash]
----
$ npm install whatwg-fetch --save
----

```js
import 'whatwg-fetch'
```

=== Response

==== HTML

[source,javascript]
----
fetch('/users.html')
  .then((res) => {
    return res.text()
  }).then((body) => {
    document.body.innerHTML = body
  })
----

==== JSON

[source,javascript]
----
fetch('/users.json')
  .then((res) => {
    return res.json()
  }).then((json) => {
    console.log('success:', json)
  }).catch((ex) => {
    console.log('failed:', ex)
  })
----

==== Response metadata

[source,javascript]
----
fetch('/users.json').then((res) => {
  console.log('Content-Type', res.headers.get('Content-Type'))
  console.log('Date', res.headers.get('Date'))
  console.log('status', res.status)
  console.log('statusText', res.statusText)
})
----

== POST Form Data

[source,javascript]
----
const form = document.querySelector('form')

fetch('/users', {
  method: 'POST',
  body: new FormData(form),
})
----

[source,javascript]
----
const fd = new FormData(form)
fd.append('foo', 'bar')

fetch('/users', {
  method: 'POST',
  body: fd,
})
----

=== POST :: jQuery と fetch API の違い

jQuery:: Form Data

fetch API:: Request Payload

==== fetch API にて Form Data でリクエストするには Content-Type を指定する

```js
headers: { 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8' }
```

- link:https://gist.github.com/umamichi/1e1f2d48d5e2a85041033619ea44a730[umamichi/fetch APIでハマったこと.md]
- link:http://qiita.com/masakielastic/items/70516e074eadf2ce09dd[Fetch API で x-www-form-urlencoded を直接指定することを避ける - Qiita]

.fetch API - POST example
```js
import queryString from 'query-string';

fetch('https://example.com', {
  headers: {
    Accept: 'application/json',
    'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
  },
  method: 'POST',
  body: queryString.stringify(this.query),
}).then(res => res.json()).then((json) => {
  console.log(json);
}).catch((ex) => {
  console.warn(ex);
});
```

query-string::
link:https://github.com/sindresorhus/query-string[sindresorhus/query-string: Parse and stringify URL query strings]


== DELETE

DELETE メソッドは GET と同様に payload body を持てないため、
POST の例で示したようなリクエストを投げると 400 Bad Request となる。

[quote, 'link:https://stackoverflow.com/questions/30334776/servlets-3-1-how-to-handle-body-in-delete-request[java - Servlets 3.1: how to handle body in DELETE request - Stack Overflow]']
DELETE is not supposed to have a body, just like GET.


== Cookie

[source,javascript]
----
fetch(url, {
  credentials: 'include',
})
----


== curl

- link:https://gist.github.com/subfuzion/08c5d85437d5d4f00e58[curl POST examples]

=== POST `application/x-www-form-urlencoded`

default:

```bash
curl -d "param1=value1&param2=value2" -X POST http://localhost:3000/data
```

explicit:

```bash
curl -d "param1=value1&param2=value2" -H "Content-Type: application/x-www-form-urlencoded" -X POST http://localhost:3000/data
```

with a data file
 
```bash
curl -d "@data.txt" -X POST http://localhost:3000/data
```

=== POST `application/json`

```bash
curl -d '{"key1":"value1", "key2":"value2"}' -H "Content-Type: application/json" -X POST http://localhost:3000/data
```

with a data file
 
```bash
curl -d "@data.json" -X POST http://localhost:3000/data
```


== Links

- link:https://developers.google.com/web/updates/2015/03/introduction-to-fetch[Introduction to fetch()  |  Web  |  Google Developers]
- link:http://tacamy.hatenablog.com/entry/2016/10/16/182658[jQuery.ajax()の代替としてFetch APIをざっくり使ってみる - tacamy.blog]
- link:http://stackoverflow.com/questions/34558264/fetch-api-with-cookie[Fetch API with Cookie \- Stack Overflow]
- link:https://github.com/expressjs/body-parser[expressjs/body-parser: Node.js body parsing middleware] +
  サーバサイド(express)でPOSTリクエストのボディ部を読み取るやつ
- link:https://github.com/facebook/react-native/issues/2538['unsupported BodyInit type' error is uncatchable · Issue #2538 · facebook/react-native]
