---
rid: 1492530
bid: javascript
rcd: nodejs-code-tips
srcpath: javascript/nodejs-code-tips.adoc
title: Node.js CODE TIPS
category: JavaScript
date: 2019.07.25
layout: refill.jade
---

== ファイル読み込み

テキストファイルの読み込みである場合`'utf-8'`のようにエンコーディングを指定する。

- File System | Node.js Documentation
  * `link:https://nodejs.org/api/fs.html#fs_fs_readfilesync_path_options[fs.readFileSync(path[, options\])]`
  * `link:https://nodejs.org/api/fs.html#fs_fs_readfile_path_options_callback[fs.readFile(path[, options\], callback)]`

[source,javascript]
----
const fs = require('fs');

// sync
const text = fs.readFileSync('./input.txt', 'utf8');

// async
fs.readFile('./input.txt', 'utf8', function(err, text) {
  if (err) throw err;
  console.log(text);
});
----

=== Shift JISファイルの読込と書込

```bash
$ npm install -S iconv-lite
```

[source,javascript]
----
const fs = require('fs');
const iconv = require('iconv-lite');

const file = fs.readFileSync('./input.txt');
const text= iconv.decode(Buffer.from(file), "Shift_JIS");
// ...
const buf = iconv.encode(text, "Shift_JIS");
fs.writeFileSync('output.txt', buf, ()=>{});
----


== ファイル書き込み

=== ファイル書き込み（上書き）

- `link:https://nodejs.org/api/fs.html#fs_fs_writefile_file_data_options_callback[fs.writeFile(file, data[, options\], callback)]`
- `link:https://nodejs.org/api/fs.html#fs_fs_writefilesync_file_data_options[fs.writeFileSync(file, data[, options\])]`

[source,javascript]
----
require("fs").writeFileSync("out.txt", "Hello!");
----

=== ファイル書き込み（追記）

- `link:https://nodejs.org/api/fs.html#fs_fs_appendfile_file_data_options_callback[fs.appendFile(file, data[, options\], callback)]`
- `link:https://nodejs.org/api/fs.html#fs_fs_appendfilesync_file_data_options[fs.appendFileSync(file, data[, options\])]`


== 1列読み込み

.sample.txt
[source]
----
red
blue
green
yellow
----

[source,javascript]
----
const fs = require('fs');
const content = fs.readFileSync('sample.txt').toString();
const colors = content.trim().split('\n');
//=> [ 'red', 'blue', 'green', 'yellow' ]
----


== ファイルコピー

- link:https://qiita.com/PianoScoreJP/items/ec3d1b64d5e3a3bfa3b4[Node.js ファイルをコピーするたぶん一番簡単な方法 - Qiita]
- link:https://qiita.com/tadnakam/items/6b6e0da5bb05c86bd573[node.js で簡単にファイルコピーができるようになってました。 - Qiita]
  * `link:https://nodejs.org/api/fs.html#fs_fs_copyfile_src_dest_flags_callback[fs.copyFile(src, dest[, flags\], callback)]`
  * `link:https://nodejs.org/api/fs.html#fs_fs_copyfile_src_dest_flags_callback[fs.copyFileSync(src, dest[, flags\])]`
```js
const fs = require('fs');
fs.createReadStream('src.txt').pipe(fs.createWriteStream('dest.txt'));
```


== CSV

- link:https://syon.github.io/refills/rid/1546773/[Node.js CSV まとめ :: JavaScript | Refills]


== URL Path Join

`url.resolve(from, to)` を使用する。
よくある join による連結ではなく、現在地と行き先を渡す。
from で指定された URL を現在地として to という行き先を命令された場合に
結局どこに行くのかを解明した結果を返す。
from は `http://` で開始する必要はない。
逆に to が `http://` から始まる URL でもよい。
それは外部サイトに移動する時と同じ挙動と言える。

- link:https://nodejs.org/api/url.html#url_url_resolve_from_to[url.resolve(from, to) - URL | Node.js Documentation]
- link:https://stackoverflow.com/questions/16301503/can-i-use-requirepath-join-to-safely-concatenate-urls[node.js - Can I use require("path").join to safely concatenate urls? - Stack Overflow]

```js
url.resolve('/japan/tokyo/shibuya', 'ebisu')
//=> '/japan/tokyo/ebisu'
url.resolve('http://world.com', 'japan')
//=> 'http://world.com/japan'
url.resolve('http://world.com/japan/tokyo/', '../osaka/')
//=> 'http://world.com/japan/osaka/'
url.resolve('http://world.com/japan/tokyo/', '/america/new-york')
//=> 'http://world.com/america/new-york'
url.resolve('http://world.com', 'https://google.com')
//=> 'https://google.com/'
```


== tktk

- link:https://www.npmjs.com/package/tktk[tktk]
