---
rid: 1498316
bid: command-prompt
rcd: batch-tips
srcpath: command-prompt/batch-tips.adoc
title: "バッチ TIPS"
category: コマンドプロンプト
date: 2017.6.24
layout: refill.jade
---


== 空行の echo

```batch
echo.
```


== 実行結果を出力しない

[quote, 'link:http://qiita.com/uhooi/items/b8b25761a5c4efe9025a[batファイルでコマンドの実行結果を出力しないようにする方法 - Qiita]']
`>` はリダイレクトといい、出力先をコマンドプロンプトでなく指定したファイルに変更します。
`nul` は空（のファイル）という意味で、書き込んでも何も起きません。
つまり、`> nul` で出力先を空のファイルに変更することで、コマンドプロンプト上には何も出力されなくなります。 +
`> nul` を付けただけだと、エラーメッセージは出力されてしまいます。
さらに `2>&1` を付けることで、エラーメッセージも出力されなくなります。

.例
```batch
C:\Windows\System32>mkdir hoge > nul

C:\Windows\System32>mkdir hoge > nul
サブディレクトリまたはファイル hoge は既に存在します。

C:\Windows\System32>rmdir hoge

C:\Windows\System32>mkdir hoge > nul 2>&1

C:\Windows\System32>mkdir hoge > nul 2>&1
```


== 引数のダブルクォーテーションを除去する

.sample.bat
```batch
echo %1
echo %~1
```

```batch
> sample.bat "Hello"
"Hello"
Hello
```


== cmd.exe のエスケープ仕様

解釈のフェーズによってエスケープ仕様が変わる。

- link:http://thinca.hatenablog.com/entry/20100210/1265813598[cmd.exe のコマンドラインの仕様を解析してみた - 永遠に未完成]


== if文の中で変数の値が反映されないとき

- link:http://dalmore.blog7.fc2.com/blog-entry-79.html[バッチファイルのif文やfor文で気をつけること]

0. `setlocal enabledelayedexpansion` を記述する（遅延環境変数の展開）
0. 変数の展開は `%` ではなく `!` で行う


== 標準出力の結果を変数に格納する

コマンドプロンプトには該当の機能がないようなので、ちょっとしたテクニックを使って実現します。
次に示す１行のコマンドは `time /T` の結果を変数 `T` に格納しています。

```batch
FOR /F "DELIMS=" %%A IN ('time /T') DO SET T=%%A
```

`ECHO %T%` とすると `15:00` のように時刻が表示されます。


== 指定したプロセスが起動中かどうか確認する

上記の応用例です。
例としてメモ帳 (notepad.exe) を起動中かどうか判定します。
PID ではなくイメージ名を使っています。

```batch
FOR /F "DELIMS=" %%A IN ('tasklist ^| find /C "notepad.exe"') DO SET CNT=%%A

IF %CNT% GTR 0 (
  echo メモ帳を開いています
) else (
  echo メモ帳を開いていません
)
```

`tasklist` でプロセスの一覧を取得し、その結果をパイプ `|` で次の処理に引き渡しています。
このときキャレット `^` を使ってエスケープする必要がある点に注意してください。
`find /C "notepad.exe"` で notepad.exe という文字列を含む行のみに絞り込み、
その行数をカウントした結果の数値を変数 `CNT` に格納しています。
`IF %CNT% GTR 0` は「もし CNT が 0 より大きかったら」という意味です。


== pwd

```batch
SET CURRENT_DIR=%cd%
```
