---
rid: 1516111
bid: chrome
rcd: cvim
srcpath: chrome/cvim.adoc
title: Chromeを素早くキーボードで操作！『cVim』の使い方
category: Chrome拡張
date: 2018.1.16
layout: refill.jade
---

:experimental:


== cVimとは

＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊

ここでは*Vimのことをよく知らない人*を対象に説明します。


== cVimにできること

- ＊＊＊＊＊＊＊＊＊＊
- ＊＊＊＊＊＊＊＊＊＊
- ＊＊＊＊＊＊＊＊＊＊


== 入手

- link:https://chrome.google.com/webstore/detail/cvim/ihlenndgcmojhcghmfjfneahoeklbjjh[cVim - Chrome ウェブストア]


== cVimrc おすすめ設定

[source,vim]
.cVimrc
----
set scalehints
set smoothscroll
let scrollduration = 300
----


== 覚えておきたいキーバインド

約150パターンあるキーバインドのうち、ひとまずこれだけ覚えておけばOKなリストを
ピックアップしてみました。デフォルト設定を前提に説明しています。

キーバインドの列は、それをローマ字入力するつもりで打ち込んでください。
例えば kbd:[gg] は G キーを2回連続で打ち込みます。
kbd:[G] は Shift キーを押しながら G キーを打ち込みます。

=== キーバインド :: スクロール

|===
|キーバインド |説明

|kbd:[j] ・ kbd:[k]
|上下に少しスクロール（右手）

|kbd:[u]
|上に半ページスクロール（右手）

|kbd:[s] ・ kbd:[w]
|上下に少しスクロール（左手）

|kbd:[d] ・ kbd:[e]
|上下に半ページスクロール（左手）

|kbd:[gg]
|ページの先頭へスクロール

|kbd:[G]
|ページの末尾へスクロール

|kbd:[gi]
|最初の入力要素にフォーカス。Googleなど多くのサイトはサイト上部に検索窓があるため、そこに素早く移動可能。

|kbd:[zz]
|cVimの " `/` " 検索でヒットしてアクティブなものが画面中央に来るところにスクロール
|===

=== キーバインド :: リンクヒント

現在画面に表示中のエリア内にあるリンク要素、入力要素、ボタン要素にヒントを表示し、
そのキーを再度押すと説明に記載の動作が実行されます。

|===
|キーバインド |説明

|kbd:[f]
|リンクをクリック

|kbd:[F]
|リンクをクリックして新しいタブで開く
|===

リンクヒントを表示させた後に Tab キーを押してからヒントを打ち込んで選択すると、
そのリンクのアドレスを表示することができます。
偶然見つけた挙動で、ドキュメントの該当箇所がわかりません。。


## 注意事項

- Webサイトによっては独自にキーボード入力を検知して動作し、cVimと競合するときがある。
  この場合はChrome右上の拡張アイコンからcVimを選択し「Enable cVim」を押して一時的にOFFにするなどして対処。
- Webページでのみ動作。ブラウザの設定画面やエラー画面では動作しない。
- Chromeを再起動したときに復元されたタブはcVimを読み込んでおらず動作しない。`F5`・`Ctrl+R`などでリロードして対処。
