---
rid: 1496490
bid: selenium
rcd: install
srcpath: selenium/install.adoc
title: Seleniumとブラウザドライバーのインストールと使い方
date: 2017.6.10
layout: refill.jade
---

この記事では、npm (Node.js) の `selenium-standalone` による
Selenium 本体と各種ブラウザドライバーのインストール方法、その使い方を説明します。

- link:https://github.com/vvo/selenium-standalone[]


== selenium-standalone でできること

Selenium Standalone Server のインストール::
link:http://www.seleniumhq.org/download/[SeleniumHQ 公式のページ] でも案内されている
Selenium の本体をダウンロードしてくれます。
- `selenium-server-standalone-3.4.0.jar`
    * from: https://selenium-release.storage.googleapis.com

Browser Drivers のインストール::
下記のような各種ブラウザのドライバをダウンロードしてくれます。
対象のブラウザやそのバージョンは設定ファイルで指定することもできます。
- `2.29-x64-chromedriver`
    * from: https://chromedriver.storage.googleapis.com
- `3.4.0-x64-IEDriverServer.exe`
    * from: https://selenium-release.storage.googleapis.com
- `0.16.0-x64-geckodriver`
    * from: https://github.com/mozilla/geckodriver/releases

Selenium Standalone Server のスタート::
ブラウザの自動操作環境を提供するサーバを開始します。
これが起動している状態でないと、スクリプトでブラウザを操作することができません。


== selenium-standalone のグローバルインストール

まずは手軽に試すことのできるグローバルインストールの方法を説明します。
任意のディレクトリで以下のコマンドを実行してください。
オプション `-g` を指定してグローバルインストールすることで、
どのディレクトリからでも Selenium のサーバを起動できるようにしています。

[source,bash]
----
$ npm install -g selenium-standalone@latest

$ selenium-standalone install
----

.コマンド実行結果の例
```bash
---
selenium install:
from: https://selenium-release.storage.googleapis.com/3.4/selenium-server-standalone-3.4.0.jar
to: /usr/local/lib/node_modules/selenium-standalone/.selenium/selenium-server/3.4.0-server.jar
---
chrome install:
from: https://chromedriver.storage.googleapis.com/2.29/chromedriver_mac64.zip
to: /usr/local/lib/node_modules/selenium-standalone/.selenium/chromedriver/2.29-x64-chromedriver
---
firefox install:
from: https://github.com/mozilla/geckodriver/releases/download/v0.16.0/geckodriver-v0.16.0-macos.tar.gz
to: /usr/local/lib/node_modules/selenium-standalone/.selenium/geckodriver/0.16.0-x64-geckodriver
```


== ブラウザドライバーのインストール


=== Google Chrome
[source,bash]
----
$ npm install -g chromedriver
----

- コマンド`chromedriver`にPATHが通っていることが要件
  * どのように紐付けているかは未調査
- link:https://www.npmjs.com/package/chromedriver[npm - chromedriver]
- link:https://sites.google.com/a/chromium.org/chromedriver/[ChromeDriver - WebDriver for Chrome]


=== Microsoft Edge

[source,bash]
----
$ npm install -g edgedriver
----

- link:https://www.npmjs.com/package/edgedriver[npm - edgedriver]
- link:https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/[WebDriver - Microsoft Edge Development]


=== Mozilla Firefox

[source,bash]
----
$ npm install -g geckodriver
----

- link:https://www.npmjs.com/package/geckodriver[npm - geckodriver]
- link:https://github.com/mozilla/geckodriver[mozilla/geckodriver]


=== Opera

[source,bash]
----
$ npm install -g operadriver
----

- link:https://www.npmjs.com/package/operadriver[npm - operadriver]
- link:https://github.com/operasoftware/operachromiumdriver[operasoftware/operachromiumdriver]


=== Safari

(未調査)

- link:https://webkit.org/blog/6900/webdriver-support-in-safari-10/[WebDriver Support in Safari 10 | WebKit]



== Seleniumサーバの開始

[source,bash]
----
$ selenium-standalone start
----


== Seleniumサーバ 開始オプション

=== DesiredCapabilities

SeleniumHQ/selenium Wiki::
- link:https://github.com/SeleniumHQ/selenium/wiki/DesiredCapabilities[DesiredCapabilities · SeleniumHQ/selenium Wiki]
- link:https://github.com/SeleniumHQ/selenium/wiki/Grid-Platforms[Grid Platforms · SeleniumHQ/selenium Wiki]

デバイス・OS・ブラウザ・バージョンを指定して生成する便利ツール::
link:https://wiki.saucelabs.com/display/DOCS/Platform+Configurator#/[Platform Configurator - The Sauce Labs Cookbook]

[cols="1,1,2", options="header"]
.browser selection
|===
|Key
|Type
|Description

|browserName
|string
|以下のうちいずれか1つ。 +
`android`, `chrome`, `firefox`, `htmlunit`, `internet explorer`, `iPhone`, `iPad`, `opera`, `safari`

|version
|string
|ブラウザのバージョン。不明の場合は空白を指定。

|platform
|string
|以下のうちいずれか1つ。 +
`WINDOWS`, `XP`, `VISTA`, `MAC`, `LINUX`, `UNIX`, `ANDROID` +
|===
